apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      # kubectl rollout history deploy nginx-deployment 에서 CHANGE-CAUSE
      annotations:
        kubernetes.io/change-cause: version 1.10.1
    spec:
      containers:
      # replicas로 사용하려는 container 정보
      - name: nginx-deployment
        image: nginx
        ports:
        - containerPort: 80
