apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-simple-pod
  labels:
    app: simple-pod
spec:
  containers:
  - name: kubernetes-simple-pod
    image: arisu1000/simple-container-app:latest
    resources:
      requests:
        cpu: 0.1
        memory: 200M
      limits:
        cpu: 0.5
        memory: 1G
    ports:
    - containerPort: 8080
    env:
    - name: TEST_ENV
      value: "test value"
    - name: HOST_NAME
      valueFrom:                    # 값을 할당하려는 것이 아니라, 다른 곳에서 참조하려는 값 설정
        fieldRef:                   # pod의 현재 설정 내용을 값으로 설정 
          fieldPath: spec.nodeName  # .fieldRef에서 어디서 값을 가져올 것인지 지정 (참조하려는 항목의 위치)
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: CPU_REQUEST
      valueFrom:
        resourceFieldRef:                       # container에 CPU. Memory 사용량을 얼마나 할당했는지에 대한 정보
          containerName: kubernetes-simple-pod  # 환경 변수 설정을 가져올 container 이름
          resource: requests.cpu                # resource 정보 
    - name: CPU_LIMIT
      valueFrom:
        resourceFieldRef:
          containerName: kubernetes-simple-pod
          resource: limits.cpu
