apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  # replicaset가 어느 pod에서 실행할 것인지
  template:
    metadata:
      name: nginx-replicaset
      labels:
        app: nginx
    # container의 구체적인 명세
    spec:
      containers:
      - name: nginx-replicaset
        image: nginx
        ports:
        - containerPort: 80
  replicas: 3
  # 어떤 label의 pod를 선택해서 관리할 것인지
  # label 기준으로 pod를 관리하기 때문에 실행 중인 pod를 중단하거나 재시작하지 않고 replication controller가 관리하는 pod를 변경할 수 있음
  selector:
    matchLabels:
      app: nginx  # spec.template.metadata.labels 와 설정이 같아야 유효한 api 요청 
     
     
     
