---
- name: Collect facts for each node
  hosts: client

  tasks:
  - name: generate facts
    setup:
    register: facts

  - name: save facts
    local_action:
      module: copy
      # 저장되어 있는 facts 값을 json으로 변경
      content: "{{ facts | to_nice_json }}"
      dest: ./{{ ansible_hostname }}_facts_by_collector.txt
